name = '3024-Day'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = 'f7f7f7'
black = '090200'
black-hg = '5b5754'
blue = '00a0e4'
blue-hg = '7f7c7b'
cursor = '494542'
cyan = 'b5e4f4'
cyan-hg = 'ccab53'
foreground = '494542'
green = '00a152'
green-hg = '3a3332'
magenta = 'a06994'
magenta-hg = 'd6d4d3'
red = 'da2c20'
red-hg = 'e8bacf'
selection-background = 'a4a1a1'
selection-foreground = 'f7f7f7'
white = 'a4a1a1'
white-hg = 'f7f7f7'
yellow = 'fcec02'
yellow-hg = '494542'
