name = 'Afterglow'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '202020'
black = '151515'
black-hg = '505050'
blue = '6c99ba'
blue-hg = '6c99ba'
cursor = 'd0d0d0'
cyan = '7dd5cf'
cyan-hg = '7dd5cf'
foreground = 'd0d0d0'
green = '7e8d50'
green-hg = '7e8d50'
magenta = '9e4e85'
magenta-hg = '9e4e85'
red = 'ac4142'
red-hg = 'ac4142'
selection-background = '303030'
selection-foreground = '202020'
white = 'd0d0d0'
white-hg = 'f5f5f5'
yellow = 'e5b566'
yellow-hg = 'e5b566'
