name = 'Apathy-dark'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '031A16'
black = '031A16'
black-hg = '2B685E'
blue = '96883E'
blue-hg = '96883E'
cursor = '81B5AC'
cyan = '963E4C'
cyan-hg = '963E4C'
foreground = '81B5AC'
green = '883E96'
green-hg = '883E96'
magenta = '4C963E'
magenta-hg = '4C963E'
red = '3E9688'
red-hg = '3E9688'
selection-background = '81B5AC'
selection-foreground = '031A16'
white = '81B5AC'
white-hg = 'D2E7E4'
yellow = '3E4C96'
yellow-hg = '3E4C96'
