name = 'Apprentice'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '323232'
black = '252525'
black-hg = '555555'
blue = '7199bc'
blue-hg = '9fbdde'
cursor = 'c7c7c7'
cyan = '719899'
cyan-hg = '6fbbbc'
foreground = 'c8c8c8'
green = '709772'
green-hg = '97bb98'
magenta = '727399'
magenta-hg = '989abc'
red = 'be7472'
red-hg = 'ff9900'
selection-background = 'c1ddff'
selection-foreground = '3e3e3e'
white = '7f7f7f'
white-hg = 'feffff'
yellow = '989772'
yellow-hg = 'fefdbc'
