name = 'Ariake-Dark'

[extras]
intellij-idea = ['']
vscode = ['Ariake Dark']
wallpaper = ['']

[colors]
background = '1F212A'
black = '5F6270'
black-hg = '5F6270'
blue = '7D7DDB'
blue-hg = '7D7DDB'
cursor = 'F0F5FA'
cyan = '84B0DE'
cyan-hg = '84B0DE'
foreground = 'F0F5FA'
green = 'cbed99'
green-hg = 'cbed99'
magenta = 'DBA1F4'
magenta-hg = 'DBA1F4'
red = 'fb7185'
red-hg = 'fb7185'
selection-background = 'F0F5FA'
selection-foreground = '1F212A'
white = 'F0F5FA'
white-hg = 'F0F5FA'
yellow = '99EDE8'
yellow-hg = '99EDE8'
