name = 'Arthur'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '1c1c1c'
black = '3d352a'
black-hg = '554444'
blue = '6495ed'
blue-hg = '87ceeb'
cursor = 'e2bbef'
cyan = 'b0c4de'
cyan-hg = 'b0c4de'
foreground = 'ddeedd'
green = '86af80'
green-hg = '88aa22'
magenta = 'deb887'
magenta-hg = '996600'
red = 'cd5c5c'
red-hg = 'cc5533'
selection-background = '4d4d4d'
selection-foreground = '1c1c1c'
white = 'bbaa99'
white-hg = 'ddccbb'
yellow = 'e8ae5b'
yellow-hg = 'ffa75d'
