name = 'Ashes-light'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = 'F3F4F5'
black = '1C2023'
black-hg = '747C84'
blue = 'AE95C7'
blue-hg = 'AE95C7'
cursor = '565E65'
cyan = '95AEC7'
cyan-hg = '95AEC7'
foreground = '565E65'
green = '95C7AE'
green-hg = '95C7AE'
magenta = 'C795AE'
magenta-hg = 'C795AE'
red = 'C7AE95'
red-hg = 'C7AE95'
selection-background = '565E65'
selection-foreground = 'F3F4F5'
white = 'C7CCD1'
white-hg = 'F3F4F5'
yellow = 'AEC795'
yellow-hg = 'AEC795'
