name = 'Astromouse'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '000000'
black = '1c1c1c'
black-hg = '3d3a3a'
blue = '77b6c5'
blue-hg = '8fa7b9'
cursor = 'ffffff'
cyan = '7fcab3'
cyan-hg = '6ec2a8'
foreground = 'ffffff'
green = '9acc79'
green-hg = '8fb676'
magenta = 'a488d9'
magenta-hg = 'bd89de'
red = 'd770af'
red-hg = 'd28abf'
selection-background = 'ffffff'
selection-foreground = '000000'
white = '8d8d8d'
white-hg = 'dad3d3'
yellow = 'd0d26b'
yellow-hg = 'c8bc45'
