name = 'AtelierSulphurpool'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '202745'
black = '202745'
black-hg = '6a7394'
blue = '3d8ed0'
blue-hg = '898ea3'
cursor = '969cb3'
cyan = '21a1c8'
cyan-hg = '9c6279'
foreground = '969cb3'
green = 'ab9639'
green-hg = '283256'
magenta = '6678cc'
magenta-hg = 'dee1f0'
red = 'c84821'
red-hg = 'c76a28'
selection-background = '5e6686'
selection-foreground = '202745'
white = '969cb3'
white-hg = 'f4f7ff'
yellow = 'c08a2f'
yellow-hg = '5e6686'
