name = 'Atelierlakeside-light'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = 'ebf8ff'
black = '161b1d'
black-hg = '5a7b8c'
blue = '257fad'
blue-hg = '257fad'
cursor = '516d7b'
cyan = '2d8f6f'
cyan-hg = '2d8f6f'
foreground = '516d7b'
green = '568c3b'
green-hg = '568c3b'
magenta = '5d5db1'
magenta-hg = '5d5db1'
red = 'd22d72'
red-hg = 'd22d72'
selection-background = '516d7b'
selection-foreground = 'ebf8ff'
white = '7ea2b4'
white-hg = 'ebf8ff'
yellow = '8a8a0f'
yellow-hg = '8a8a0f'
