name = 'Atelierdune-dark'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '20201d'
black = '20201d'
black-hg = '7d7a68'
blue = '6684e1'
blue-hg = '6684e1'
cursor = 'a6a28c'
cyan = '1fad83'
cyan-hg = '1fad83'
foreground = 'a6a28c'
green = '60ac39'
green-hg = '60ac39'
magenta = 'b854d4'
magenta-hg = 'b854d4'
red = 'd73737'
red-hg = 'd73737'
selection-background = 'a6a28c'
selection-foreground = '20201d'
white = 'a6a28c'
white-hg = 'fefbec'
yellow = 'cfb017'
yellow-hg = 'cfb017'
