name = 'Atelierforest-light'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = 'f1efee'
black = '1b1918'
black-hg = '766e6b'
blue = '407ee7'
blue-hg = '407ee7'
cursor = '68615e'
cyan = '00ad9c'
cyan-hg = '00ad9c'
foreground = '68615e'
green = '5ab738'
green-hg = '5ab738'
magenta = '6666ea'
magenta-hg = '6666ea'
red = 'f22c40'
red-hg = 'f22c40'
selection-background = '68615e'
selection-foreground = 'f1efee'
white = 'a8a19f'
white-hg = 'f1efee'
yellow = 'd5911a'
yellow-hg = 'd5911a'
