name = 'Atelierdune-light'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = 'fefbec'
black = '20201d'
black-hg = '7d7a68'
blue = '6684e1'
blue-hg = '6684e1'
cursor = '6e6b5e'
cyan = '1fad83'
cyan-hg = '1fad83'
foreground = '6e6b5e'
green = '60ac39'
green-hg = '60ac39'
magenta = 'b854d4'
magenta-hg = 'b854d4'
red = 'd73737'
red-hg = 'd73737'
selection-background = '6e6b5e'
selection-foreground = 'fefbec'
white = 'a6a28c'
white-hg = 'fefbec'
yellow = 'cfb017'
yellow-hg = 'cfb017'
