name = 'Atelierheath-dark'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '1b181b'
black = '1b181b'
black-hg = '776977'
blue = '516aec'
blue-hg = '516aec'
cursor = 'ab9bab'
cyan = '159393'
cyan-hg = '159393'
foreground = 'ab9bab'
green = '379a37'
green-hg = '379a37'
magenta = '7b59c0'
magenta-hg = '7b59c0'
red = 'ca402b'
red-hg = 'ca402b'
selection-background = 'ab9bab'
selection-foreground = '1b181b'
white = 'ab9bab'
white-hg = 'f7f3f7'
yellow = 'bb8a35'
yellow-hg = 'bb8a35'
