name = 'Awesome'

[extras]
vscode = ['Gruvbox Light Hard']
wallpaper = ['~/.config/gtheme/wallpapers/Gruvbox/gruv-paint.png']

[colors]
background = 'FFF4DE'
black = 'fbf1c7'
black-hg = '282828'
blue = '458588'
blue-hg = '076678'
cursor = '272727'
cyan = 'B0D4D0'
cyan-hg = 'B0D4D0'
foreground = '272727'
green = '98971a'
green-hg = '79740e'
magenta = 'b16286'
magenta-hg = '8f3f71'
red = 'cc241d'
red-hg = '9d0006'
selection-background = '272727'
selection-foreground = 'FFF4DE'
white = '7c6f64'
white-hg = '272727'
yellow = 'd79921'
yellow-hg = 'b57614'
