name = 'Ayu'

[extras]
vscode = ['Ayu Dark']
wallpaper = ['']

[colors]
background = '0e1419'
black = '000000'
black-hg = '323232'
blue = '36a3d9'
blue-hg = '68d4ff'
cursor = 'f19618'
cyan = '95e5cb'
cyan-hg = 'c7fffc'
foreground = 'e5e1cf'
green = 'b8cc52'
green-hg = 'e9fe83'
magenta = 'f07078'
magenta-hg = 'ffa3aa'
red = 'ff3333'
red-hg = 'ff6565'
selection-background = '243340'
selection-foreground = '0e1419'
white = 'ffffff'
white-hg = 'ffffff'
yellow = 'e6c446'
yellow-hg = 'fff778'
