name = 'Base16-Default-Dark'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '181818'
black = '181818'
black-hg = '585858'
blue = '7cafc2'
blue-hg = '7cafc2'
cursor = 'd8d8d8'
cyan = '86c1b9'
cyan-hg = '86c1b9'
foreground = 'd8d8d8'
green = 'a1b56c'
green-hg = 'a1b56c'
magenta = 'ba8baf'
magenta-hg = 'ba8baf'
red = 'ab4642'
red-hg = 'ab4642'
selection-background = 'd8d8d8'
selection-foreground = 'd8d8d8'
white = 'd8d8d8'
white-hg = 'f8f8f8'
yellow = 'f7ca88'
yellow-hg = 'f7ca88'
