name = 'Baskerville-Eldoradodark'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '292929'
black = '4e4e4e'
black-hg = '777777'
blue = '5879af'
blue-hg = 'b3d1ff'
cursor = 'a2a2a2'
cyan = '008592'
cyan-hg = '79e0ed'
foreground = 'a2a2a2'
green = '468459'
green-hg = '9ddeaf'
magenta = '9c6594'
magenta-hg = 'fabdf0'
red = 'a9635d'
red-hg = 'ffbbb2'
selection-background = 'a2a2a2'
selection-foreground = '292929'
white = 'cfcfcf'
white-hg = 'ffffff'
yellow = '84763d'
yellow-hg = 'e0ce91'
