name = 'Baskerville-ivorylight'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = 'fef9ec'
black = 'c5c1b4'
black-hg = 'a1a6b2'
blue = '208ffb'
blue-hg = '0065ca'
cursor = '6d727e'
cyan = '00a4c1'
cyan-hg = '007693'
foreground = '6d727e'
green = '00a250'
green-hg = '007427'
magenta = 'd160c4'
magenta-hg = 'a03196'
red = 'e75c58'
red-hg = 'b22b31'
selection-background = '6d727e'
selection-foreground = 'fef9ec'
white = '3e424d'
white-hg = '282c36'
yellow = 'a08a00'
yellow-hg = '715f00'
