name = 'Bespin-light'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = 'baae9e'
black = '28211c'
black-hg = '666666'
blue = '5ea6ea'
blue-hg = '5ea6ea'
cursor = '5e5d5c'
cyan = 'afc4db'
cyan-hg = 'afc4db'
foreground = '5e5d5c'
green = '54be0d'
green-hg = '54be0d'
magenta = '9b859d'
magenta-hg = '9b859d'
red = 'cf6a4c'
red-hg = 'cf6a4c'
selection-background = '5e5d5c'
selection-foreground = 'baae9e'
white = '8a8986'
white-hg = 'baae9e'
yellow = 'f9ee98'
yellow-hg = 'f9ee98'
