name = 'BirdsOfParadise'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '2a1e1d'
black = '573d25'
black-hg = '9a6b49'
blue = '5a86ac'
blue-hg = 'b8d3ed'
cursor = '573d25'
cyan = '74a5ac'
cyan-hg = '92ced6'
foreground = 'dfdab7'
green = '6ba08a'
green-hg = '94d7ba'
magenta = 'ab80a6'
magenta-hg = 'd09dca'
red = 'be2d26'
red-hg = 'e84526'
selection-background = '563c27'
selection-foreground = '2a1e1d'
white = 'dfdab7'
white-hg = 'fff9d4'
yellow = 'e99c29'
yellow-hg = 'd0d04f'
