name = 'Bitmute'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '000000'
black = '282828'
black-hg = '494949'
blue = '68668f'
blue-hg = '73718f'
cursor = 'ffffff'
cyan = '688891'
cyan-hg = '758c93'
foreground = 'ffffff'
green = '719d72'
green-hg = '839d84'
magenta = '966894'
magenta-hg = '987397'
red = 'b76969'
red-hg = 'b87e7e'
selection-background = 'ffffff'
selection-foreground = '000000'
white = '8e8e8e'
white-hg = 'aeaeae'
yellow = '909858'
yellow-hg = '919864'
