name = 'BlackAndWhite-Dark'

[extras]
vscode = ['White']
wallpaper = ['~/.config/gtheme/wallpapers/BlackAndWhite/city.jpg']

[colors]
background = '000000'
black = 'ffffff'
black-hg = 'ffffff'
blue = 'ffffff'
blue-hg = 'ffffff'
cursor = 'ffffff'
cyan = 'ffffff'
cyan-hg = 'ffffff'
foreground = 'ffffff'
green = 'ffffff'
green-hg = 'ffffff'
magenta = 'ffffff'
magenta-hg = 'ffffff'
red = 'ffffff'
red-hg = 'ffffff'
selection-background = 'ffffff'
selection-foreground = '000000'
white = 'ffffff'
white-hg = 'ffffff'
yellow = 'ffffff'
yellow-hg = 'ffffff'
