name = 'Blood-Moon'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '10100E'
black = '10100E'
black-hg = '696969'
blue = '0087BD'
blue-hg = '007FFF'
cursor = 'C6C6C4'
cyan = '20B2AA'
cyan-hg = '00CCCC'
foreground = 'C6C6C4'
green = '009F6B'
green-hg = '03C03C'
magenta = '9A4EAE'
magenta-hg = 'FF1493'
red = 'C40233'
red-hg = 'FF2400'
selection-background = 'C6C6C4'
selection-foreground = '10100E'
white = 'C6C6C4'
white-hg = 'FFFAFA'
yellow = 'FFD700'
yellow-hg = 'FDFF00'
