name = 'Borland'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '0000a3'
black = '4e4e4e'
black-hg = '7c7c7c'
blue = '96cafd'
blue-hg = 'b5dcfe'
cursor = 'ffa460'
cyan = 'c6c4fd'
cyan-hg = 'dfdffe'
foreground = 'ffff4d'
green = 'a7ff60'
green-hg = 'ceffab'
magenta = 'ff73fd'
magenta-hg = 'ff9cfe'
red = 'ff6b60'
red-hg = 'ffb6b0'
selection-background = 'a3a3a3'
selection-foreground = '0000a3'
white = 'eeeeee'
white-hg = 'ffffff'
yellow = 'ffffb6'
yellow-hg = 'ffffcb'
