name = 'Breeze'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '232627'
black = '232627'
black-hg = '232627'
blue = '1d99f3'
blue-hg = '1d99f3'
cursor = 'fcfcfc'
cyan = '1abc9c'
cyan-hg = '16a085'
foreground = 'fcfcfc'
green = '11d116'
green-hg = '11d116'
magenta = '9b59b6'
magenta-hg = '8e44ad'
red = 'ed1515'
red-hg = 'ed1515'
selection-background = 'fcfcfc'
selection-foreground = '232627'
white = 'fcfcfc'
white-hg = 'ffffff'
yellow = 'f67400'
yellow-hg = 'f67400'
