name = 'Bright-light'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = 'ffffff'
black = '000000'
black-hg = 'b0b0b0'
blue = '6fb3d2'
blue-hg = '6fb3d2'
cursor = '505050'
cyan = '76c7b7'
cyan-hg = '76c7b7'
foreground = '505050'
green = 'a1c659'
green-hg = 'a1c659'
magenta = 'd381c3'
magenta-hg = 'd381c3'
red = 'fb0120'
red-hg = 'fb0120'
selection-background = '505050'
selection-foreground = 'ffffff'
white = 'e0e0e0'
white-hg = 'ffffff'
yellow = 'fda331'
yellow-hg = 'fda331'
