name = 'Brogrammer'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '131313'
black = '1f1f1f'
black-hg = 'd6dae4'
blue = '2a84d2'
blue-hg = '0f80d5'
cursor = 'b9b9b9'
cyan = '0f80d5'
cyan-hg = '0f7cda'
foreground = 'd6dae4'
green = '2cc55d'
green-hg = '1dd260'
magenta = '4e59b7'
magenta-hg = '524fb9'
red = 'f71118'
red-hg = 'de342e'
selection-background = '1f1f1f'
selection-foreground = '131313'
white = 'd6dae4'
white-hg = 'ffffff'
yellow = 'ecb90f'
yellow-hg = 'f2bd09'
