name = 'Campbell'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '0c0c0c'
black = '0c0c0c'
black-hg = '767676'
blue = '0037da'
blue-hg = '3b78ff'
cursor = 'cccccc'
cyan = '3a96dd'
cyan-hg = '61d6d6'
foreground = 'cccccc'
green = '13a10e'
green-hg = '16c60c'
magenta = '881798'
magenta-hg = 'b4009e'
red = 'c50f1f'
red-hg = 'e74856'
selection-background = 'cccccc'
selection-foreground = '0c0c0c'
white = 'cccccc'
white-hg = 'f2f2f2'
yellow = 'c19c00'
yellow-hg = 'f9f1a5'
