name = 'Chalk-light'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = 'f5f5f5'
black = '151515'
black-hg = '505050'
blue = '6fc2ef'
blue-hg = '6fc2ef'
cursor = '303030'
cyan = '12cfc0'
cyan-hg = '12cfc0'
foreground = '303030'
green = 'acc267'
green-hg = 'acc267'
magenta = 'e1a3ee'
magenta-hg = 'e1a3ee'
red = 'fb9fb1'
red-hg = 'fb9fb1'
selection-background = '303030'
selection-foreground = 'f5f5f5'
white = 'd0d0d0'
white-hg = 'f5f5f5'
yellow = 'ddb26f'
yellow-hg = 'ddb26f'
