name = 'Chalkboard'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '29262f'
black = '000000'
black-hg = '323232'
blue = '7372c3'
blue-hg = 'aaaadb'
cursor = 'd9e6f2'
cyan = '72c2c3'
cyan-hg = 'aadadb'
foreground = 'd9e6f2'
green = '72c373'
green-hg = 'aadbaa'
magenta = 'c372c2'
magenta-hg = 'dbaada'
red = 'c37372'
red-hg = 'dbaaaa'
selection-background = '073642'
selection-foreground = '29262f'
white = 'd9d9d9'
white-hg = 'ffffff'
yellow = 'c2c372'
yellow-hg = 'dadbaa'
