name = 'CLRS'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = 'ffffff'
black = '000000'
black-hg = '545753'
blue = '125ccf'
blue-hg = '156ffe'
cursor = '6fd2fc'
cyan = '32c2c0'
cyan-hg = '39d5ce'
foreground = '262626'
green = '32895c'
green-hg = '2cc631'
magenta = '9f00bc'
magenta-hg = 'e800b0'
red = 'f72729'
red-hg = 'fb0416'
selection-background = '6fd2fc'
selection-foreground = 'ffffff'
white = 'b2b2b2'
white-hg = 'ededec'
yellow = 'f96f1c'
yellow-hg = 'fcd627'
