name = 'Cobalt-Neon'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '142838'
black = '142630'
black-hg = 'fff688'
blue = '8ff586'
blue-hg = '3c7dd2'
cursor = 'c4206f'
cyan = '8ff586'
cyan-hg = '6cbc67'
foreground = '8ff586'
green = '3aa5ff'
green-hg = '8ff586'
magenta = '781aa0'
magenta-hg = '8230a7'
red = 'ff2320'
red-hg = 'd4312e'
selection-background = '084fb0'
selection-foreground = '142838'
white = 'ba45b1'
white-hg = '8ff586'
yellow = 'e9e75c'
yellow-hg = 'e9f06d'
