name = 'Colorfu.colors'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '000000'
black = '151515'
black-hg = '696969'
blue = 'a6e2f0'
blue-hg = '79d2ff'
cursor = 'ffffff'
cyan = '5f868f'
cyan-hg = '87a8af'
foreground = 'ffffff'
green = 'a6e25f'
green-hg = 'a6e179'
magenta = 'e85b92'
magenta-hg = 'bb5d79'
red = 'ff8eaf'
red-hg = 'ed4c7a'
selection-background = 'ffffff'
selection-foreground = '000000'
white = 'd5f1f2'
white-hg = 'e2f1f6'
yellow = 'f8e578'
yellow-hg = 'ffdf6b'
