name = 'CrayonPonyFish'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '140607'
black = '2a1a1c'
black-hg = '3c2a2e'
blue = '8b87af'
blue-hg = 'cfc9ff'
cursor = '685259'
cyan = 'e8a766'
cyan-hg = 'ffceae'
foreground = '685259'
green = '579523'
green-hg = '8dff56'
magenta = '682e50'
magenta-hg = 'fb6cb9'
red = '90002a'
red-hg = 'c5245c'
selection-background = '2a1a1c'
selection-foreground = '140607'
white = '685259'
white-hg = 'af949d'
yellow = 'aa301b'
yellow-hg = 'c7371d'
