name = 'Dark-Pastel'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '000000'
black = '000000'
black-hg = '545454'
blue = '5555ff'
blue-hg = '5555ff'
cursor = 'bbbbbb'
cyan = '55ffff'
cyan-hg = '55ffff'
foreground = 'ffffff'
green = '55ff55'
green-hg = '55ff55'
magenta = 'ff55ff'
magenta-hg = 'ff55ff'
red = 'ff5555'
red-hg = 'ff5555'
selection-background = 'b5d5ff'
selection-foreground = '000000'
white = 'bbbbbb'
white-hg = 'ffffff'
yellow = 'ffff55'
yellow-hg = 'ffff55'
