name = 'Darktooth'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '282828'
black = '282828'
black-hg = '32302f'
blue = '076678'
blue-hg = '83a598'
cursor = 'fdf4c1'
cyan = '00a7af'
cyan-hg = '3fd7e5'
foreground = 'fdf4c1'
green = '79740e'
green-hg = 'b8bb26'
magenta = '8f3f71'
magenta-hg = 'd3869b'
red = '9d0006'
red-hg = 'fb4933'
selection-background = 'fdf4c1'
selection-foreground = '282828'
white = 'fdf4c1'
white-hg = 'ffffc8'
yellow = 'b57614'
yellow-hg = 'fabd2f'
