name = 'Derp'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '000000'
black = '111111'
black-hg = '666666'
blue = '5297cf'
blue-hg = '74b8ef'
cursor = 'ffffff'
cyan = '5e7175'
cyan-hg = 'a3babf'
foreground = 'ffffff'
green = 'aece91'
green-hg = 'cfefb3'
magenta = '963c59'
magenta-hg = 'b85e7b'
red = 'd36265'
red-hg = 'ef8171'
selection-background = 'ffffff'
selection-foreground = '000000'
white = 'bebebe'
white-hg = 'ffffff'
yellow = 'e7e18c'
yellow-hg = 'fff796'
