name = 'Desert'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '333333'
black = '4d4d4d'
black-hg = '545454'
blue = 'cd853f'
blue-hg = '87ceff'
cursor = '00ff00'
cyan = 'ffa0a0'
cyan-hg = 'ffd700'
foreground = 'ffffff'
green = '98fb98'
green-hg = '55ff55'
magenta = 'ffdead'
magenta-hg = 'ff55ff'
red = 'ff2b2b'
red-hg = 'ff5555'
selection-background = 'b5d5ff'
selection-foreground = '333333'
white = 'f5deb3'
white-hg = 'ffffff'
yellow = 'f0e68c'
yellow-hg = 'ffff55'
