name = 'Digerati'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '000000'
black = '303030'
black-hg = '5f5f5f'
blue = '426870'
blue-hg = '4a7781'
cursor = 'ffffff'
cyan = '4bb5c1'
cyan-hg = '4bb5c1'
foreground = 'ffffff'
green = 'b1d631'
green-hg = 'a6cd07'
magenta = '6d506d'
magenta-hg = 'ff3b77'
red = 'c03000'
red-hg = 'ff3a78'
selection-background = 'ffffff'
selection-foreground = '000000'
white = 'e2e2e5'
white-hg = 'e2e2e5'
yellow = 'fecf35'
yellow-hg = 'b5c865'
