name = 'Dkeg-redphoenix'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '111111'
black = '131313'
black-hg = 'd1d1d1'
blue = '6f6f6f'
blue-hg = 'ededed'
cursor = 'ffffff'
cyan = 'aaa998'
cyan-hg = 'f2361e'
foreground = 'ffffff'
green = '4c3a3d'
green-hg = 'df9767'
magenta = '909090'
magenta-hg = 'ed4b19'
red = '2d2d2d'
red-hg = 'd2c3ad'
selection-background = 'ffffff'
selection-foreground = '111111'
white = 'b1b1b1'
white-hg = 'fa390f'
yellow = '4e4e4e'
yellow-hg = 'e1e1e1'
