name = 'Dkegtar.colors'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '000000'
black = '03010f'
black-hg = 'ab9e9e'
blue = '6067ac'
blue-hg = 'd0ae58'
cursor = 'd3d3d3'
cyan = '7c83c0'
cyan-hg = 'f4e199'
foreground = 'd3d3d3'
green = '353b64'
green-hg = 'bbada9'
magenta = '624d19'
magenta-hg = 'd7b559'
red = '503b43'
red-hg = 'b28930'
selection-background = 'd3d3d3'
selection-foreground = '000000'
white = '9a600f'
white-hg = 'f6f4df'
yellow = '8c2424'
yellow-hg = 'c37305'
