name = 'Dkeg-catchmeifyoucan'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '170f0d'
black = '130f0c'
black-hg = 'c69f77'
blue = 'aa8d70'
blue-hg = 'e0e0e2'
cursor = 'f9f9f9'
cyan = 'c4bfbf'
cyan-hg = 'eae3dc'
foreground = 'f9f9f9'
green = '8d7f85'
green-hg = 'd5c6b8'
magenta = 'b9a38d'
magenta-hg = 'e4dad2'
red = '604c38'
red-hg = 'cab9a8'
selection-background = 'f9f9f9'
selection-foreground = '170f0d'
white = 'c4ae99'
white-hg = 'f6f2f0'
yellow = '907256'
yellow-hg = 'dcd1c7'
