name = 'Dkeg-canvasedpastel'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '170f0d'
black = '26251c'
black-hg = '999f91'
blue = '534d35'
blue-hg = 'c4b67a'
cursor = '746c48'
cyan = '7b8574'
cyan-hg = 'd3d4b6'
foreground = '746c48'
green = '3d4339'
green-hg = 'b2b08c'
magenta = '646756'
magenta-hg = 'cfc995'
red = '323027'
red-hg = '9b9773'
selection-background = '746c48'
selection-foreground = '170f0d'
white = '837b61'
white-hg = 'd6d3ac'
yellow = '443b2c'
yellow-hg = 'c4bb8c'
