name = 'Dracula'

[extras]
intellij-idea = ['Dracula Colorful']
vscode = ['Dracula']
wallpaper = ['~/.config/gtheme/wallpapers/Dracula/arch-linux-light.png']

[colors]
background = '1e1f28'
black = '000000'
black-hg = '545454'
blue = 'bd92f8'
blue-hg = 'bd92f8'
cursor = 'bbbbbb'
cyan = '8ae9fc'
cyan-hg = '8ae9fc'
foreground = 'f8f8f2'
green = '50fa7b'
green-hg = '50fa7b'
magenta = 'ff78c5'
magenta-hg = 'ff78c5'
red = 'ff5555'
red-hg = 'ff5454'
selection-background = '44475a'
selection-foreground = '1e1f28'
white = 'bbbbbb'
white-hg = 'ffffff'
yellow = 'f0fa8b'
yellow-hg = 'f0fa8b'
