name = 'Earthsong'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '282420'
black = '111417'
black-hg = '665e54'
blue = '1397b9'
blue-hg = '5ed9ff'
cursor = 'f6f6ec'
cyan = '4f9452'
cyan-hg = '83ef88'
foreground = 'e5c6a8'
green = '84c44b'
green-hg = '97e035'
magenta = 'd0623c'
magenta-hg = 'ff9168'
red = 'c84134'
red-hg = 'ff6459'
selection-background = '111417'
selection-foreground = '282420'
white = 'e5c5a9'
white-hg = 'f6f6ec'
yellow = 'f4ae2e'
yellow-hg = 'dfd561'
