name = 'Embers-light'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = 'DBD6D1'
black = '16130F'
black-hg = '5A5047'
blue = '6D5782'
blue-hg = '6D5782'
cursor = '433B32'
cyan = '576D82'
cyan-hg = '576D82'
foreground = '433B32'
green = '57826D'
green-hg = '57826D'
magenta = '82576D'
magenta-hg = '82576D'
red = '826D57'
red-hg = '826D57'
selection-background = '433B32'
selection-foreground = 'DBD6D1'
white = 'A39A90'
white-hg = 'DBD6D1'
yellow = '6D8257'
yellow-hg = '6D8257'
