name = 'Euphrasia'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = 'cfcfd9'
black = '192033'
black-hg = '666666'
blue = '355c9a'
blue-hg = '45a3e6'
cursor = '1c2027'
cyan = '258f8f'
cyan-hg = '60c6c8'
foreground = '1c2027'
green = '38912b'
green-hg = '93c724'
magenta = '7c4f9f'
magenta-hg = 'c953ef'
red = 'a62a3e'
red-hg = 'f04758'
selection-background = '1c2027'
selection-foreground = 'cfcfd9'
white = '77858c'
white-hg = 'c0c0c0'
yellow = 'b27d12'
yellow-hg = 'ddb62b'
