name = 'Everforest-Light-Medium'

[extras]
vscode = ['Everforest Light']
wallpaper = ['']

[colors]
background = 'fdf6e3'
black = '4a555b'
black-hg = '525c62'
blue = '7fbbb3'
blue-hg = '7fbbb3'
cursor = '7fbbb3'
cyan = '83c092'
cyan-hg = '83c092'
foreground = '323d43'
green = 'a7c080'
green-hg = 'a7c080'
magenta = 'd699b6'
magenta-hg = 'd699b6'
red = 'e68183'
red-hg = 'e68183'
selection-background = 'd3dbc8'
selection-foreground = 'e4e1cd'
white = 'f3efda'
white-hg = 'f3efda'
yellow = 'dbbc7f'
yellow-hg = 'dbbc7f'
