name = 'Fideloper'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '282f32'
black = '282f32'
black-hg = '092027'
blue = '2e78c1'
blue-hg = '7c84c4'
cursor = 'd35f5a'
cyan = '309185'
cyan-hg = '81908f'
foreground = 'dad9df'
green = 'edb7ab'
green-hg = 'd35f5a'
magenta = 'c0226e'
magenta-hg = '5b5db2'
red = 'ca1d2c'
red-hg = 'd35f5a'
selection-background = 'eeb7ab'
selection-foreground = '282f32'
white = 'e9e2cd'
white-hg = 'fcf4de'
yellow = 'b7aa9a'
yellow-hg = 'a86571'
