name = 'Fishbone'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '000000'
black = '293b3b'
black-hg = '344040'
blue = '416ea5'
blue-hg = '5177a5'
cursor = 'ffffff'
cyan = '714da5'
cyan-hg = '7859a5'
foreground = 'ffffff'
green = '41a551'
green-hg = '51a55f'
magenta = 'bf6053'
magenta-hg = 'bf6e63'
red = 'bf5357'
red-hg = 'bf6367'
selection-background = 'ffffff'
selection-foreground = '000000'
white = '876868'
white-hg = '876f6f'
yellow = 'aea64f'
yellow-hg = 'aea75d'
