name = 'FrontEndDelight'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '1b1b1d'
black = '242426'
black-hg = '5eac6c'
blue = '2c70b7'
blue-hg = '3393c9'
cursor = 'cccccc'
cyan = '3ba0a5'
cyan-hg = '4ebce5'
foreground = 'acacac'
green = '565746'
green-hg = '74eb4c'
magenta = 'f02d4e'
magenta-hg = 'e75e4e'
red = 'f8501a'
red-hg = 'f64319'
selection-background = 'e96153'
selection-foreground = '1b1b1d'
white = 'acacac'
white-hg = '8b735a'
yellow = 'f9761d'
yellow-hg = 'fcc224'
