name = 'Galaxy'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '1c2836'
black = '000000'
black-hg = '545454'
blue = '589cf5'
blue-hg = '589cf5'
cursor = 'bbbbbb'
cyan = '1e9ee6'
cyan-hg = '3978bb'
foreground = 'ffffff'
green = '20af89'
green-hg = '34bb99'
magenta = '934d95'
magenta-hg = 'e75598'
red = 'f9555f'
red-hg = 'fa8b8e'
selection-background = 'b4d5ff'
selection-foreground = '1c2836'
white = 'bbbbbb'
white-hg = 'ffffff'
yellow = 'fdf029'
yellow-hg = 'ffff55'
