name = 'Github'

[extras]
vscode = ['GitHub Plus']
wallpaper = ['~/.config/gtheme/wallpapers/GitHub/github.jpg']

[colors]
background = 'f4f4f4'
black = '3e3e3e'
black-hg = '666666'
blue = '003e8a'
blue-hg = '2e6cba'
cursor = '3f3f3f'
cyan = '89d1ec'
cyan-hg = '1cfafe'
foreground = '3e3e3e'
green = '07962a'
green-hg = '87d5a2'
magenta = 'e94691'
magenta-hg = 'ffa29f'
red = '970b16'
red-hg = 'de0000'
selection-background = 'a9c1e2'
selection-foreground = 'f4f4f4'
white = 'ffffff'
white-hg = 'ffffff'
yellow = 'f7edc7'
yellow-hg = 'f0cf06'
