name = 'GoaBase'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '2f0033'
black = '880041'
black-hg = '411a6d'
blue = '000482'
blue-hg = 'b90003'
cursor = '1a6500'
cyan = '3affff'
cyan-hg = 'c8f9f3'
foreground = 'f6ed00'
green = '249000'
green-hg = '5743ff'
magenta = 'f43bff'
magenta-hg = '9a5952'
red = 'f78000'
red-hg = 'f800e1'
selection-background = '100a24'
selection-foreground = '2f0033'
white = '000000'
white-hg = 'f5f4fb'
yellow = 'f40000'
yellow-hg = 'ea00d7'
