name = 'Google-dark'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '1d1f21'
black = '1d1f21'
black-hg = '969896'
blue = '3971ED'
blue-hg = '3971ED'
cursor = 'c5c8c6'
cyan = '3971ED'
cyan-hg = '3971ED'
foreground = 'c5c8c6'
green = '198844'
green-hg = '198844'
magenta = 'A36AC7'
magenta-hg = 'A36AC7'
red = 'CC342B'
red-hg = 'CC342B'
selection-background = 'c5c8c6'
selection-foreground = '1d1f21'
white = 'c5c8c6'
white-hg = 'ffffff'
yellow = 'FBA922'
yellow-hg = 'FBA922'
