name = 'Gotham'

[extras]
vscode = ['Gotham']
wallpaper = ['']

[colors]
background = '0a0f14'
black = '0a0f14'
black-hg = '10151b'
blue = '195465'
blue-hg = '093748'
cursor = '98d1ce'
cyan = '33859d'
cyan-hg = '599caa'
foreground = '98d1ce'
green = '26a98b'
green-hg = '081f2d'
magenta = '4e5165'
magenta-hg = '888ba5'
red = 'c33027'
red-hg = 'd26939'
selection-background = '98d1ce'
selection-foreground = '0a0f14'
white = '98d1ce'
white-hg = 'd3ebe9'
yellow = 'edb54b'
yellow-hg = '245361'
