name = 'Grayscale-light'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = 'f7f7f7'
black = '101010'
black-hg = '525252'
blue = '686868'
blue-hg = '686868'
cursor = '464646'
cyan = '868686'
cyan-hg = '868686'
foreground = '464646'
green = '8e8e8e'
green-hg = '8e8e8e'
magenta = '747474'
magenta-hg = '747474'
red = '7c7c7c'
red-hg = '7c7c7c'
selection-background = '464646'
selection-foreground = 'f7f7f7'
white = 'b9b9b9'
white-hg = 'f7f7f7'
yellow = 'a0a0a0'
yellow-hg = 'a0a0a0'
