name = 'Greenscreen-dark'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '001100'
black = '001100'
black-hg = '007700'
blue = '009900'
blue-hg = '009900'
cursor = '00bb00'
cyan = '005500'
cyan-hg = '005500'
foreground = '00bb00'
green = '00bb00'
green-hg = '00bb00'
magenta = '00bb00'
magenta-hg = '00bb00'
red = '007700'
red-hg = '007700'
selection-background = '00bb00'
selection-foreground = '001100'
white = '00bb00'
white-hg = '00ff00'
yellow = '007700'
yellow-hg = '007700'
