name = 'Greenscreen-light'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '00ff00'
black = '001100'
black-hg = '007700'
blue = '009900'
blue-hg = '009900'
cursor = '005500'
cyan = '005500'
cyan-hg = '005500'
foreground = '005500'
green = '00bb00'
green-hg = '00bb00'
magenta = '00bb00'
magenta-hg = '00bb00'
red = '007700'
red-hg = '007700'
selection-background = '005500'
selection-foreground = '00ff00'
white = '00bb00'
white-hg = '00ff00'
yellow = '007700'
yellow-hg = '007700'
