name = 'Gruvbox-Light'

[extras]
vscode = ['Gruvbox Light Medium']
wallpaper = ['~/.config/gtheme/wallpapers/Gruvbox/dark-archlinux.png']

[colors]
background = 'fbf1c7'
black = 'fbf1c7'
black-hg = '282828'
blue = '458588'
blue-hg = '076678'
cursor = '928374'
cyan = '689d6a'
cyan-hg = '427b58'
foreground = '3c3836'
green = '98971a'
green-hg = '79740e'
magenta = 'b16286'
magenta-hg = '8f3f71'
red = 'cc241d'
red-hg = '9d0006'
selection-background = '928374'
selection-foreground = '3c3836'
white = '7c6f64'
white-hg = '928374'
yellow = 'd79921'
yellow-hg = 'b57614'
