name = 'Gruvbox-Dark'

[extras]
vscode = ['Gruvbox Dark Medium']
wallpaper = ['~/.config/gtheme/wallpapers/Gruvbox/light-archlinux.png']

[colors]
background = '282828'
black = '282828'
black-hg = '928374'
blue = '458588'
blue-hg = '83a598'
cursor = '928374'
cyan = '689d6a'
cyan-hg = '8ec07c'
foreground = 'ebdbb2'
green = '98971a'
green-hg = 'b8bb26'
magenta = 'b16286'
magenta-hg = 'd3869b'
red = 'cc241d'
red-hg = 'fb4934'
selection-background = '3c3836'
selection-foreground = '928374'
white = 'a89984'
white-hg = '928374'
yellow = 'd79921'
yellow-hg = 'fabd2d'
