name = 'Gslobnature-suede'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '170f0d'
black = '392925'
black-hg = '544b2e'
blue = '7b854e'
blue-hg = '70a16c'
cursor = '746c48'
cyan = '5c5142'
cyan-hg = '778725'
foreground = '746c48'
green = '908f32'
green-hg = 'c3c13d'
magenta = '6b5644'
magenta-hg = '98724c'
red = '98724c'
red-hg = 'af652f'
selection-background = '746c48'
selection-foreground = '170f0d'
white = 'c8b55b'
white-hg = 'e4dc8c'
yellow = 'aa964c'
yellow-hg = 'c8b55b'
