name = 'Gutterslob-lumifoo'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '1e2021'
black = '515151'
black-hg = '707172'
blue = '6b85c2'
blue-hg = 'afc4e9'
cursor = '888a8c'
cyan = '5c9d88'
cyan-hg = 'a4d0c1'
foreground = '888a8c'
green = '65a446'
green-hg = 'aed49b'
magenta = '9e6bb8'
magenta-hg = 'd2b1e2'
red = 'bf6382'
red-hg = 'eaaec2'
selection-background = '888a8c'
selection-foreground = '1e2021'
white = '919191'
white-hg = 'd0d0d0'
yellow = 'ad8a43'
yellow-hg = 'd4c3a0'
