name = 'Harmonic16-light'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = 'f7f9fb'
black = '0b1c2c'
black-hg = '627e99'
blue = '8b56bf'
blue-hg = '8b56bf'
cursor = '405c79'
cyan = '568bbf'
cyan-hg = '568bbf'
foreground = '405c79'
green = '56bf8b'
green-hg = '56bf8b'
magenta = 'bf568b'
magenta-hg = 'bf568b'
red = 'bf8b56'
red-hg = 'bf8b56'
selection-background = '405c79'
selection-foreground = 'f7f9fb'
white = 'cbd6e2'
white-hg = 'f7f9fb'
yellow = '8bbf56'
yellow-hg = '8bbf56'
