name = 'Homebrew'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '000000'
black = '000000'
black-hg = '666666'
blue = '0000b2'
blue-hg = '0000ff'
cursor = '23ff18'
cyan = '00a6b2'
cyan-hg = '00e5e5'
foreground = '00ff00'
green = '00a600'
green-hg = '00d900'
magenta = 'b200b2'
magenta-hg = 'e500e5'
red = '990000'
red-hg = 'e50000'
selection-background = '083905'
selection-foreground = '000000'
white = 'bebebe'
white-hg = 'e5e5e5'
yellow = '999900'
yellow-hg = 'e5e500'
