name = 'Hybrid'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '161718'
black = '2a2e33'
black-hg = '1d1e21'
blue = '6d90b0'
blue-hg = '4b6b88'
cursor = 'b7bcb9'
cyan = '7fbeb3'
cyan-hg = '4d7b73'
foreground = 'b7bcb9'
green = 'b3be5a'
green-hg = '788331'
magenta = 'a07eab'
magenta-hg = '6e4f79'
red = 'b74d50'
red-hg = '8c2d32'
selection-background = '1e1f22'
selection-foreground = '161718'
white = 'b5b8b6'
white-hg = '5a6169'
yellow = 'e3b55e'
yellow-hg = 'e5894f'
