name = 'Iiamblack'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '000000'
black = '393939'
black-hg = '474747'
blue = '6d9cbe'
blue-hg = 'd0d0ff'
cursor = 'ffffff'
cyan = '435d75'
cyan-hg = '6e98a4'
foreground = 'ffffff'
green = '519f50'
green-hg = 'a5c261'
magenta = '9f5079'
magenta-hg = 'a761c2'
red = 'da4939'
red-hg = 'ff6c5c'
selection-background = 'ffffff'
selection-foreground = '000000'
white = 'dddddd'
white-hg = 'dddddd'
yellow = 'cc7833'
yellow-hg = 'bc9458'
