name = 'Japanesque'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '1d1d1d'
black = '343835'
black-hg = '585a58'
blue = '4c99d3'
blue-hg = '135879'
cursor = 'eccf4f'
cyan = '389aac'
cyan-hg = '76bbca'
foreground = 'f7f6ec'
green = '7bb75b'
green-hg = '767e2b'
magenta = 'a57fc4'
magenta-hg = '5f4190'
red = 'ce3e60'
red-hg = 'd18ea6'
selection-background = '165776'
selection-foreground = '1d1d1d'
white = 'f9faf6'
white-hg = 'b1b5ae'
yellow = 'e8b32a'
yellow-hg = '77592e'
