name = 'Jasonwryan'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '000000'
black = '222222'
black-hg = '454545'
blue = '4c8ea1'
blue-hg = '6bc1d0'
cursor = 'ffffff'
cyan = '7c9aa6'
cyan-hg = '8fadbf'
foreground = 'ffffff'
green = '6c7e55'
green-hg = '7db37d'
magenta = '956d9d'
magenta-hg = 'c18fcb'
red = '9e5641'
red-hg = 'cc896d'
selection-background = 'ffffff'
selection-foreground = '000000'
white = '909090'
white-hg = 'ffffff'
yellow = 'caaf2b'
yellow-hg = 'bfb556'
