name = 'JetBrains-Darcula'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '202020'
black = '000000'
black-hg = '545454'
blue = '4581eb'
blue-hg = '6d9df1'
cursor = 'ffffff'
cyan = '33c2c1'
cyan-hg = '60d3d1'
foreground = 'adadad'
green = '126e00'
green-hg = '67ff4f'
magenta = 'fa54ff'
magenta-hg = 'fb82ff'
red = 'fa5355'
red-hg = 'fb7172'
selection-background = '1a3272'
selection-foreground = '202020'
white = 'adadad'
white-hg = 'eeeeee'
yellow = 'c2c300'
yellow-hg = 'ffff00'
