name = 'Jwr-dark'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '000000'
black = '333333'
black-hg = '3d3d3d'
blue = '395573'
blue-hg = '477ab3'
cursor = 'ffffff'
cyan = '31658c'
cyan-hg = '6096bf'
foreground = 'ffffff'
green = '287373'
green-hg = '53a6a6'
magenta = '5e468c'
magenta-hg = '7e62b3'
red = '8c4665'
red-hg = 'bf4d80'
selection-background = 'ffffff'
selection-foreground = '000000'
white = '899ca1'
white-hg = 'c0c0c0'
yellow = '7c7c99'
yellow-hg = '9e9ecb'
