name = 'Lavandula'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '050014'
black = '230045'
black-hg = '362c45'
blue = '4f4a7f'
blue-hg = '8e86df'
cursor = '8b91fa'
cyan = '57767f'
cyan-hg = '9ad3df'
foreground = '736d7c'
green = '337e6f'
green-hg = '52e0c4'
magenta = '593f7e'
magenta-hg = 'a675df'
red = '7c1525'
red-hg = 'df5066'
selection-background = '36323b'
selection-foreground = '050014'
white = '736d7c'
white-hg = '8b91fa'
yellow = '7f6f49'
yellow-hg = 'e0c286'
