name = 'LiquidCarbon'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '2f2f2f'
black = '000000'
black-hg = '000000'
blue = '0099cc'
blue-hg = '0099cc'
cursor = 'ffffff'
cyan = '79c4cc'
cyan-hg = '79c4cc'
foreground = 'afc2c2'
green = '549a6f'
green-hg = '549a6f'
magenta = 'cc68c8'
magenta-hg = 'cc68c8'
red = 'ff2f2f'
red-hg = 'ff2f2f'
selection-background = '7cbeff'
selection-foreground = '2f2f2f'
white = 'bccccc'
white-hg = 'bccccc'
yellow = 'ccac00'
yellow-hg = 'ccac00'
