name = 'LiquidCarbonTransparentInverse'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '000000'
black = 'bbcbcc'
black-hg = 'ffffff'
blue = '0099cc'
blue-hg = '0099cc'
cursor = 'ffffff'
cyan = '79c4cc'
cyan-hg = '79c4cc'
foreground = 'afc2c2'
green = '549a6f'
green-hg = '549a6f'
magenta = 'cc68c8'
magenta-hg = 'cc68c8'
red = 'ff2f2f'
red-hg = 'ff2f2f'
selection-background = '7cbeff'
selection-foreground = '000000'
white = '000000'
white-hg = '000000'
yellow = 'ccac00'
yellow-hg = 'ccac00'
