name = 'Marrakesh-light'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = 'faf0a5'
black = '201602'
black-hg = '6c6823'
blue = '477ca1'
blue-hg = '477ca1'
cursor = '5f5b17'
cyan = '75a738'
cyan-hg = '75a738'
foreground = '5f5b17'
green = '18974e'
green-hg = '18974e'
magenta = '8868b3'
magenta-hg = '8868b3'
red = 'c35359'
red-hg = 'c35359'
selection-background = '5f5b17'
selection-foreground = 'faf0a5'
white = '948e48'
white-hg = 'faf0a5'
yellow = 'a88339'
yellow-hg = 'a88339'
