name = 'Materia'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '263238'
black = '2c393f'
black-hg = '707880'
blue = 'ea9560'
blue-hg = 'ea9560'
cursor = 'c9ccd3'
cyan = 'ec5f67'
cyan-hg = 'ffffff'
foreground = 'c9ccd3'
green = '82aaff'
green-hg = '82aaff'
magenta = 'ec5f67'
magenta-hg = 'ec5f67'
red = '8bd649'
red-hg = '8bd649'
selection-background = 'c9ccd3'
selection-foreground = '263238'
white = 'cdd3de'
white-hg = 'd5dbe6'
yellow = '89ddff'
yellow-hg = '89ddff'
