name = 'Mathias'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '000000'
black = '000000'
black-hg = '545454'
blue = 'c48dff'
blue-hg = '5555ff'
cursor = 'bbbbbb'
cyan = '67d9f0'
cyan-hg = '55ffff'
foreground = 'bbbbbb'
green = 'a6e32d'
green-hg = '55ff55'
magenta = 'fa2573'
magenta-hg = 'ff55ff'
red = 'e52222'
red-hg = 'ff5555'
selection-background = '545454'
selection-foreground = '000000'
white = 'f2f2f2'
white-hg = 'ffffff'
yellow = 'fc951e'
yellow-hg = 'ffff55'
