name = 'Mikado'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '000000'
black = '322a2c'
black-hg = '46423b'
blue = '6a8c8c'
blue-hg = '74999e'
cursor = 'ffffff'
cyan = '757978'
cyan-hg = '9fa590'
foreground = 'ffffff'
green = '9b9329'
green-hg = 'b4aa30'
magenta = '856774'
magenta-hg = '9c818e'
red = 'a04363'
red-hg = 'ae837a'
selection-background = 'ffffff'
selection-foreground = '000000'
white = 'bcbcaf'
white-hg = 'c1c4bc'
yellow = 'bf7a29'
yellow-hg = 'c7a551'
