name = 'Mikazuki'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '000000'
black = '2a1d17'
black-hg = '4f362b'
blue = '3ea290'
blue-hg = '8ca8a3'
cursor = 'ffffff'
cyan = '8c16da'
cyan-hg = 'a167c7'
foreground = 'ffffff'
green = '3ea250'
green-hg = '6cb87a'
magenta = 'ff850d'
magenta-hg = 'ffa64f'
red = 'da1657'
red-hg = 'da4375'
selection-background = 'ffffff'
selection-foreground = '000000'
white = 'e9e9e9'
white-hg = 'fdfdfd'
yellow = 'e3d33d'
yellow-hg = 'e3da84'
