name = 'Mocha-dark'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '3B3228'
black = '3B3228'
black-hg = '7e705a'
blue = '8ab3b5'
blue-hg = '8ab3b5'
cursor = 'd0c8c6'
cyan = '7bbda4'
cyan-hg = '7bbda4'
foreground = 'd0c8c6'
green = 'beb55b'
green-hg = 'beb55b'
magenta = 'a89bb9'
magenta-hg = 'a89bb9'
red = 'cb6077'
red-hg = 'cb6077'
selection-background = 'd0c8c6'
selection-foreground = '3B3228'
white = 'd0c8c6'
white-hg = 'f5eeeb'
yellow = 'f4bc87'
yellow-hg = 'f4bc87'
