name = 'Molokai'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '121212'
black = '121212'
black-hg = '545454'
blue = '0f7fcf'
blue-hg = '00afff'
cursor = 'bbbbbb'
cyan = '42a7cf'
cyan-hg = '50cdfe'
foreground = 'bbbbbb'
green = '97e123'
green-hg = 'b0e05e'
magenta = '8700ff'
magenta-hg = 'af87ff'
red = 'fa2573'
red-hg = 'f5669c'
selection-background = 'b4d5ff'
selection-foreground = '121212'
white = 'bbbbbb'
white-hg = 'ffffff'
yellow = 'dfd460'
yellow-hg = 'fef26c'
