name = 'MonaLisa'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '110b0d'
black = '341a0d'
black-hg = '874227'
blue = '515b5c'
blue-hg = '9eb2b3'
cursor = 'c36c32'
cyan = '588056'
cyan-hg = '89cc8e'
foreground = 'f6d56a'
green = '626132'
green-hg = 'b3b163'
magenta = '9b1d29'
magenta-hg = 'ff5b6a'
red = '9b281b'
red-hg = 'ff4230'
selection-background = 'f6d56a'
selection-foreground = '110b0d'
white = 'f6d75c'
white-hg = 'ffe597'
yellow = 'c26e27'
yellow-hg = 'ff9565'
