name = 'Monotheme'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '000000'
black = '000000'
black-hg = '202020'
blue = '999999'
blue-hg = '7c7c7c'
cursor = 'ffffff'
cyan = '8a8a8a'
cyan-hg = 'c0c0c0'
foreground = 'ffffff'
green = 'c4c4c4'
green-hg = 'f8f8f8'
magenta = '717171'
magenta-hg = 'adadad'
red = '6b6b6b'
red-hg = '464646'
selection-background = 'ffffff'
selection-foreground = '000000'
white = 'b5cabb'
white-hg = '99ac9e'
yellow = 'b3b3b3'
yellow-hg = 'eeeeee'
