name = 'Monokai-Pro-(Filter-Spectrum)'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '363537'
black = '363537'
black-hg = '69676c'
blue = 'fd9353'
blue-hg = 'fd9353'
cursor = 'f7f1ff'
cyan = '5ad4e6'
cyan-hg = '5ad4e6'
foreground = 'f7f1ff'
green = '7bd88f'
green-hg = '7bd88f'
magenta = '948ae3'
magenta-hg = '948ae3'
red = 'fc618d'
red-hg = 'fc618d'
selection-background = 'f7f1ff'
selection-foreground = '363537'
white = 'f7f1ff'
white-hg = 'f7f1ff'
yellow = 'fce566'
yellow-hg = 'fce566'
