name = 'Mountain'

[extras]
vscode = ['Rosé Pine Dawn']
wallpaper = ['~/.config/gtheme/wallpapers/Mountain/mountain.png']

[colors]
background = 'faf4ed'
black = 'D5D3D3'
black-hg = 'D5D3D3'
blue = '9fb0c4'
blue-hg = '9fb0c4'
cursor = '34383e'
cyan = '9cbfbd'
cyan-hg = '9cbfbd'
foreground = '34383e'
green = '8dc39c'
green-hg = '8dc39c'
magenta = '9a78aa'
magenta-hg = '9a78aa'
red = 'd28484'
red-hg = 'd28484'
selection-background = '34383e'
selection-foreground = 'faf4ed'
white = '34383e'
white-hg = '34383e'
yellow = 'cba78a'
yellow-hg = 'cba78a'
