name = 'Muse'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '000000'
black = '2e3436'
black-hg = '555753'
blue = '425387'
blue-hg = '4a5a8d'
cursor = 'ffffff'
cyan = '06989a'
cyan-hg = '12bccb'
foreground = 'ffffff'
green = '447241'
green-hg = '27a343'
magenta = '965d98'
magenta-hg = '893c8c'
red = 'a31604'
red-hg = 'c60001'
selection-background = 'ffffff'
selection-foreground = '000000'
white = 'd3d7cf'
white-hg = 'eeeeec'
yellow = 'c1951a'
yellow-hg = 'd5a30e'
