name = 'Muziecapastelwhite'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '000000'
black = '646e5b'
black-hg = '88927e'
blue = '69b2d6'
blue-hg = '95a9d6'
cursor = 'ffffff'
cyan = '69e1d3'
cyan-hg = '95e1d2'
foreground = 'ffffff'
green = 'a7e160'
green-hg = 'bde18b'
magenta = 'a073d6'
magenta-hg = 'b59fd6'
red = 'db7464'
red-hg = 'dba08f'
selection-background = 'ffffff'
selection-foreground = '000000'
white = '9ea894'
white-hg = 'c9d0c2'
yellow = 'dbd560'
yellow-hg = 'dbda8b'
