name = 'Navy-and-ivory'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '021b21'
black = '032c36'
black-hg = '065f73'
blue = '61778d'
blue-hg = '2e3340'
cursor = 'e8dfd6'
cyan = '44b5b1'
cyan-hg = '9ed9d8'
foreground = 'e8dfd6'
green = '7cbf9e'
green-hg = 'a2d9b1'
magenta = 'ff5879'
magenta-hg = 'ff99a1'
red = 'c2454e'
red-hg = 'ef5847'
selection-background = 'e8dfd6'
selection-foreground = '021b21'
white = 'f2f1b9'
white-hg = 'f6f6c9'
yellow = '8a7a63'
yellow-hg = 'beb090'
