name = 'Nightfly'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '011627'
black = '1d3b53'
black-hg = '7c8f8f'
blue = '82aaff'
blue-hg = '82aaff'
cursor = '9ca1aa'
cyan = '7fdbca'
cyan-hg = '7fdbca'
foreground = 'acb4c2'
green = 'a1cd5e'
green-hg = '21c7a8'
magenta = 'c792ea'
magenta-hg = 'ae81ff'
red = 'fc514e'
red-hg = 'ff5874'
selection-background = 'acb4c2'
selection-foreground = 'fafafa'
white = 'a1aab8'
white-hg = 'd6deeb'
yellow = 'e3d18a'
yellow-hg = 'ecc48d'
