name = 'Night'

[extras]
intellij-idea = ['']
vscode = ['']
wallpaper = ['~/.config/gtheme/wallpapers/Elektropunk/elektro-city.jpg']

[colors]
background = '061115'
black = '1C252C'
black-hg = '1C252C'
blue = '6791C9'
blue-hg = '6791C9'
cursor = 'D9D7D6'
cyan = '67AFC1'
cyan-hg = '67AFC1'
foreground = 'D9D7D6'
green = '78B892'
green-hg = '78B892'
magenta = 'BC83E3'
magenta-hg = 'BC83E3'
red = 'DF5B61'
red-hg = 'DF5B61'
selection-background = 'D9D7D6'
selection-foreground = '061115'
white = 'D9D7D6'
white-hg = 'D9D7D6'
yellow = 'DE8F78'
yellow-hg = 'DE8F78'
