name = 'Novel'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = 'dfdbc3'
black = '000000'
black-hg = '7f7f7f'
blue = '0000cc'
blue-hg = '0000cc'
cursor = '73635a'
cyan = '0087cc'
cyan-hg = '0086cb'
foreground = '3b2322'
green = '009600'
green-hg = '009600'
magenta = 'cc00cc'
magenta-hg = 'cc00cc'
red = 'cc0000'
red-hg = 'cc0000'
selection-background = 'a4a390'
selection-foreground = 'dfdbc3'
white = 'cccccc'
white-hg = 'ffffff'
yellow = 'd06b00'
yellow-hg = 'd06b00'
