name = 'NumixDarkest'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '282828'
black = '555555'
black-hg = '888888'
blue = '0d68a8'
blue-hg = '0f75bd'
cursor = 'a2a2a2'
cyan = '288e9c'
cyan-hg = '37c3d6'
foreground = 'a2a2a2'
green = '61bc3b'
green-hg = '86df5d'
magenta = '744560'
magenta-hg = '9e5e83'
red = '9c3528'
red-hg = 'd64937'
selection-background = 'a2a2a2'
selection-foreground = '282828'
white = 'a2a2a2'
white-hg = 'f9f9f9'
yellow = 'f3b43a'
yellow-hg = 'fdd75a'
