name = 'Oceanic-Next'

[extras]
vscode = ['Oceanic Next']
wallpaper = ['']

[colors]
background = '1b2b34'
black = '343d46'
black-hg = '343d46'
blue = '6699cc'
blue-hg = '6699cc'
cursor = 'd8dee9'
cyan = '5fb3b3'
cyan-hg = '5fb3b3'
foreground = 'd8dee9'
green = '99C794'
green-hg = '99C794'
magenta = 'c594c5'
magenta-hg = 'c594c5'
red = 'EC5f67'
red-hg = 'EC5f67'
selection-background = 'd8dee9'
selection-foreground = '1b2b34'
white = 'd8dee9'
white-hg = 'd8dee9'
yellow = 'FAC863'
yellow-hg = 'FAC863'
