name = 'Ocean-light'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = 'eff1f5'
black = '2b303b'
black-hg = '65737e'
blue = '8fa1b3'
blue-hg = '8fa1b3'
cursor = '4f5b66'
cyan = '96b5b4'
cyan-hg = '96b5b4'
foreground = '4f5b66'
green = 'a3be8c'
green-hg = 'a3be8c'
magenta = 'b48ead'
magenta-hg = 'b48ead'
red = 'bf616a'
red-hg = 'bf616a'
selection-background = '4f5b66'
selection-foreground = 'eff1f5'
white = 'c0c5ce'
white-hg = 'eff1f5'
yellow = 'ebcb8b'
yellow-hg = 'ebcb8b'
