name = 'Ocean'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '214fbc'
black = '000000'
black-hg = '666666'
blue = '0000b2'
blue-hg = '0000ff'
cursor = '7f7f7f'
cyan = '00a6b2'
cyan-hg = '00e5e5'
foreground = 'ffffff'
green = '00a600'
green-hg = '00d900'
magenta = 'b200b2'
magenta-hg = 'e500e5'
red = '990000'
red-hg = 'e50000'
selection-background = '216dff'
selection-foreground = '214fbc'
white = 'bebebe'
white-hg = 'e5e5e5'
yellow = '999900'
yellow-hg = 'e5e500'
