name = 'OK100-Matrix'

[extras]
vscode = ['Matrix']
wallpaper = ['~/.config/gtheme/wallpapers/Matrix/black.png']

[colors]
background = '000000'
black = '000000'
black-hg = '000000'
blue = '005500'
blue-hg = '005500'
cursor = '00cc00'
cyan = '00cc00'
cyan-hg = '55ff55'
foreground = '00cc00'
green = '00cc00'
green-hg = '55ff55'
magenta = '55ff55'
magenta-hg = '55ff55'
red = '55ff55'
red-hg = '55ff55'
selection-background = '00cc00'
selection-foreground = '000000'
white = '00cc00'
white-hg = '00cc00'
yellow = '00cc00'
yellow-hg = '55ff55'
