name = 'OneDark'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '282c34'
black = '282c34'
black-hg = '393e48'
blue = '61afef'
blue-hg = '61afef'
cursor = 'cccccc'
cyan = '56b6c2'
cyan-hg = '56b6c2'
foreground = '979eab'
green = '98c379'
green-hg = '56b6c2'
magenta = 'be5046'
magenta-hg = 'be5046'
red = 'e06c75'
red-hg = 'd19a66'
selection-background = '979eab'
selection-foreground = '282c34'
white = '979eab'
white-hg = 'abb2bf'
yellow = 'e5c07b'
yellow-hg = 'e5c07b'
