name = 'Orangish'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '000000'
black = '251f1f'
black-hg = '5e5e5e'
blue = '46aede'
blue-hg = '46aede'
cursor = 'ffffff'
cyan = 'd6dbac'
cyan-hg = 'd6dbac'
foreground = 'ffffff'
green = '94e76b'
green-hg = '95e76b'
magenta = 'e32c57'
magenta-hg = 'e32c57'
red = 'eb4509'
red-hg = 'eb4509'
selection-background = 'ffffff'
selection-foreground = '000000'
white = 'efefef'
white-hg = 'efefef'
yellow = 'ffac18'
yellow-hg = 'ffac18'
