name = 'Oxide'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '212121'
black = '212121'
black-hg = '212121'
blue = '6699cc'
blue-hg = '6699cc'
cursor = 'c0c5ce'
cyan = '5fb3b3'
cyan-hg = '5fb3b3'
foreground = 'c0c5ce'
green = 'a6bc69'
green-hg = 'a6bc69'
magenta = 'c594c5'
magenta-hg = 'c594c5'
red = 'e57373'
red-hg = 'e57373'
selection-background = 'c0c5ce'
selection-foreground = '212121'
white = 'c0c5ce'
white-hg = 'f3f4f5'
yellow = 'fac863'
yellow-hg = 'fac863'
