name = 'Paraiso-dark'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '2f1d2e'
black = '2f1d2e'
black-hg = '776d70'
blue = '05b6ef'
blue-hg = '05b6ef'
cursor = 'a39d9b'
cyan = '5bc4be'
cyan-hg = '5bc4be'
foreground = 'a39d9b'
green = '48b685'
green-hg = '48b685'
magenta = '805ba3'
magenta-hg = '805ba3'
red = 'ef6154'
red-hg = 'ef6154'
selection-background = '4f414c'
selection-foreground = '2f1d2e'
white = 'a39d9b'
white-hg = 'e6e9da'
yellow = 'fec418'
yellow-hg = 'fec418'
