name = 'PaulMillr'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '000000'
black = '2a2a2a'
black-hg = '666666'
blue = '396ad6'
blue-hg = '7099ec'
cursor = '4c4c4c'
cyan = '66ccff'
cyan-hg = '79def1'
foreground = 'f1f1f1'
green = '78ff0e'
green-hg = '66ff66'
magenta = 'b348bd'
magenta-hg = 'da66e5'
red = 'ff0000'
red-hg = 'ff007f'
selection-background = '414141'
selection-foreground = '000000'
white = 'bababa'
white-hg = 'ffffff'
yellow = 'e6be00'
yellow-hg = 'f3d64d'
