name = 'PencilDark'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '202020'
black = '202020'
black-hg = '414141'
blue = '008ec4'
blue-hg = '20bafb'
cursor = '20bafb'
cyan = '20a4b9'
cyan-hg = '4fb8cc'
foreground = 'f0f0f0'
green = '10a778'
green-hg = '5ed6ae'
magenta = '523b78'
magenta-hg = '6854de'
red = 'c30670'
red-hg = 'fb0079'
selection-background = 'b6d6fc'
selection-foreground = '202020'
white = 'd9d9d9'
white-hg = 'f0f0f0'
yellow = 'a79c14'
yellow-hg = 'f3e42f'
