name = 'Phrak1'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '000000'
black = '000000'
black-hg = '545054'
blue = '0000a8'
blue-hg = '5054f8'
cursor = 'a8a8a8'
cyan = '00a8a8'
cyan-hg = '50fcf8'
foreground = 'a8a8a8'
green = '00a800'
green-hg = '50fc50'
magenta = 'a800a8'
magenta-hg = 'f854f8'
red = 'a80000'
red-hg = 'f85450'
selection-background = 'a8a8a8'
selection-foreground = '000000'
white = 'a8a8a8'
white-hg = 'f8fcf8'
yellow = 'a85400'
yellow-hg = 'f8fc50'
