name = 'Pnevma'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '1c1c1c'
black = '2f2e2d'
black-hg = '4a4845'
blue = '7fa5bd'
blue-hg = 'a1bdce'
cursor = 'e3c8ae'
cyan = '8adbb4'
cyan-hg = 'b1e7dd'
foreground = 'd0d0d0'
green = '90a57d'
green-hg = 'afbea2'
magenta = 'c79ec4'
magenta-hg = 'd7beda'
red = 'a36666'
red-hg = 'd78787'
selection-background = '4d4d4d'
selection-foreground = '1c1c1c'
white = 'd0d0d0'
white-hg = 'efefef'
yellow = 'd7af87'
yellow-hg = 'e4c9af'
