name = 'Roseate'

[extras]
vscode = ['Roseate']
wallpaper = ['~/.config/gtheme/wallpapers/Roseate/flower.jpg']

[colors]
background = '2C2833'
black = '502b3c'
black-hg = '502b3c'
blue = 'B7CDF2'
blue-hg = 'B7CDF2'
cursor = 'C2ADF8'
cyan = '7BC7B1'
cyan-hg = '7BC7B1'
foreground = 'C2ADF8'
green = 'C0CFC1'
green-hg = 'C0CFC1'
magenta = 'EC3B9A'
magenta-hg = 'EC3B9A'
red = 'FD526F'
red-hg = 'FD526F'
selection-background = 'C2ADF8'
selection-foreground = '2C2833'
white = 'FFF0F5'
white-hg = 'FFF0F5'
yellow = 'FAC96F'
yellow-hg = 'FAC96F'
