name = 'Rose-Pine-Moon'

[extras]
vscode = ['Rosé Pine Moon']
wallpaper = ['']

[colors]
background = '232136'
black = '393552'
black-hg = '817c9c'
blue = '9ccfd8'
blue-hg = '9ccfd8'
cursor = '59546d'
cyan = 'ea9a97'
cyan-hg = 'ea9a97'
foreground = 'e0def4'
green = '3e8fb0'
green-hg = '3e8fb0'
magenta = 'c4a7e7'
magenta-hg = 'c4a7e7'
red = 'eb6f92'
red-hg = 'eb6f92'
selection-background = '312f44'
selection-foreground = 'e0def4'
white = 'e0def4'
white-hg = 'e0def4'
yellow = 'f6c177'
yellow-hg = 'f6c177'
