name = 'Rose-Pine-Dawn'

[extras]
vscode = ['Rosé Pine Dawn']
wallpaper = ['~/.config/gtheme/wallpapers/Rose-Pine/Ashim.jpg']

[colors]
background = 'faf4ed'
black = 'f2e9de'
black-hg = '6e6a86'
blue = '56949f'
blue-hg = '56949f'
cursor = '9893a5'
cyan = 'd7827e'
cyan-hg = 'd7827e'
foreground = '575279'
green = '286983'
green-hg = '286983'
magenta = '907aa9'
magenta-hg = '907aa9'
red = 'b4637a'
red-hg = 'b4637a'
selection-background = 'eee9e6'
selection-foreground = '575279'
white = '575279'
white-hg = '575279'
yellow = 'ea9d34'
yellow-hg = 'ea9d34'
