name = 'Se'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '000000'
black = '252525'
black-hg = '454545'
blue = '435e87'
blue-hg = '587aa4'
cursor = 'ffffff'
cyan = '5e7175'
cyan-hg = 'a3babf'
foreground = 'ffffff'
green = 'a6e22e'
green-hg = 'b6e354'
magenta = '789ec6'
magenta-hg = '46a4ff'
red = 'ff9f95'
red-hg = 'ff8d80'
selection-background = 'ffffff'
selection-foreground = '000000'
white = 'dbdcdc'
white-hg = 'fdfdfd'
yellow = 'fd971f'
yellow-hg = 'fd971f'
