name = 'Seti'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '111213'
black = '323232'
black-hg = '323232'
blue = '43a5d5'
blue-hg = '43a5d5'
cursor = 'e2be21'
cyan = '8ec43d'
cyan-hg = '8ec43d'
foreground = 'cacecd'
green = '8ec43d'
green-hg = '8ec43d'
magenta = '8b57b5'
magenta-hg = '8b57b5'
red = 'c22832'
red-hg = 'c22832'
selection-background = '303233'
selection-foreground = '111213'
white = 'eeeeee'
white-hg = 'ffffff'
yellow = 'e0c64f'
yellow-hg = 'e0c64f'
