name = 'ShadesOfPurple'

[extras]
intellij-idea = ['']
vscode = ['Shades of Purple']
wallpaper = ['~/.config/gtheme/wallpapers/purple-triangles.jpg']

[colors]
background = '2D2B55'
black = '808080'
black-hg = '808080'
blue = 'B261FD'
blue-hg = 'B261FD'
cursor = 'cec5ff'
cyan = '89D9E0'
cyan-hg = '89D9E0'
foreground = 'cec5ff'
green = '99EA89'
green-hg = '99EA89'
magenta = 'F993FD'
magenta-hg = 'F993FD'
red = 'FD618B'
red-hg = 'FD618B'
selection-background = 'cec5ff'
selection-foreground = '2D2B55'
white = 'c7c7c7'
white-hg = 'c7c7c7'
yellow = 'F8CE00'
yellow-hg = 'F8CE00'
