name = 'Shaman'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '001014'
black = '012026'
black-hg = '374350'
blue = '449985'
blue-hg = '61d4b9'
cursor = '49fcd5'
cyan = '5c7e19'
cyan-hg = '98cf28'
foreground = '405555'
green = '00a940'
green-hg = '2aea5e'
magenta = '00599c'
magenta-hg = '1298ff'
red = 'b12f2c'
red-hg = 'ff4242'
selection-background = '415554'
selection-foreground = '001014'
white = '405554'
white-hg = '58fad6'
yellow = '5d8aa9'
yellow-hg = '8dd3fd'
