name = 'Shapeshifter-light'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = 'f9f9f9'
black = '000000'
black-hg = '343434'
blue = '3b48e3'
blue-hg = '3b48e3'
cursor = '102015'
cyan = '23edda'
cyan-hg = '23edda'
foreground = '102015'
green = '0ed839'
green-hg = '0ed839'
magenta = 'f996e2'
magenta-hg = 'f996e2'
red = 'e92f2f'
red-hg = 'e92f2f'
selection-background = '102015'
selection-foreground = 'f9f9f9'
white = 'ababab'
white-hg = 'f9f9f9'
yellow = 'dddd13'
yellow-hg = 'dddd13'
