name = 'Shic'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '000000'
black = '494949'
black-hg = '484848'
blue = 'a0c3c0'
blue-hg = '507f7c'
cursor = 'ffffff'
cyan = '695935'
cyan-hg = '927c4b'
foreground = 'ffffff'
green = '588f7a'
green-hg = '326f58'
magenta = '735e74'
magenta-hg = 'a387a6'
red = 'b9716e'
red-hg = '8f5a58'
selection-background = 'ffffff'
selection-foreground = '000000'
white = 'b1b1b1'
white-hg = 'c7c7c7'
yellow = 'aaa857'
yellow-hg = 'c7c575'
