name = 'Solarized-Darcula'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '3d3f41'
black = '25292a'
black-hg = '25292a'
blue = '2074c7'
blue-hg = '2074c7'
cursor = '708183'
cyan = '15968d'
cyan-hg = '15968d'
foreground = 'd2d8d9'
green = '629655'
green-hg = '629655'
magenta = '797fd4'
magenta-hg = '797fd4'
red = 'f24840'
red-hg = 'f24840'
selection-background = '214283'
selection-foreground = '3d3f41'
white = 'd2d8d9'
white-hg = 'd2d8d9'
yellow = 'b68800'
yellow-hg = 'b68800'
