name = 'Solarized-Light'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = 'fdf6e3'
black = 'e4e4e4'
black-hg = 'ffffd7'
blue = '0087ff'
blue-hg = '808080'
cursor = '52676f'
cyan = '00afaf'
cyan-hg = '8a8a8a'
foreground = '52676f'
green = '5f8700'
green-hg = '585858'
magenta = 'af005f'
magenta-hg = '5f5faf'
red = 'd70000'
red-hg = 'd75f00'
selection-background = 'e9e2cb'
selection-foreground = 'fcf4dc'
white = '262626'
white-hg = '1c1c1c'
yellow = 'af8700'
yellow-hg = '626262'
