name = 'Source-Code-X'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '1f1f24'
black = '4e596b'
black-hg = '91a0b1'
blue = '9586f4'
blue-hg = '53a4fb'
cursor = '7F7F7F'
cyan = '79c8b6'
cyan-hg = '83d2c0'
foreground = '000000'
green = '74b391'
green-hg = 'aef37c'
magenta = 'fb5ea3'
magenta-hg = 'fb5ea3'
red = 'fb695d'
red-hg = 'fb695d'
selection-background = '000000'
selection-foreground = '1f1f24'
white = 'BFBFBF'
white-hg = '91a0b1'
yellow = 'fc8e3e'
yellow-hg = 'fc8e3e'
