name = 'SpaceGray-Eighties'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '212121'
black = '15171c'
black-hg = '545454'
blue = '5485c0'
blue-hg = '4d83d0'
cursor = 'bbbbbb'
cyan = '57c2c0'
cyan-hg = '83e8e4'
foreground = 'bdb9ae'
green = '80a763'
green-hg = '93d393'
magenta = 'bf83c0'
magenta-hg = 'ff55ff'
red = 'ec5f67'
red-hg = 'ff6973'
selection-background = '262e35'
selection-foreground = '212121'
white = 'eeece7'
white-hg = 'ffffff'
yellow = 'fdc253'
yellow-hg = 'ffd156'
