name = 'Substrata'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '191c25'
black = '2e313d'
black-hg = '5b5f71'
blue = '8296b0'
blue-hg = 'a0b9d8'
cursor = 'b5b4c9'
cyan = '659ea2'
cyan-hg = '7dc2c7'
foreground = 'b5b4c9'
green = '76a065'
green-hg = '92c47e'
magenta = 'a18daf'
magenta-hg = 'c6aed7'
red = 'cf8164'
red-hg = 'fe9f7c'
selection-background = 'b5b4c9'
selection-foreground = '191c25'
white = 'b5b4c9'
white-hg = 'f0ecfe'
yellow = 'ab924c'
yellow-hg = 'd2b45f'
