name = 'Swayr'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '1c1709'
black = '1c1709'
black-hg = '4f4939'
blue = '315094'
blue-hg = '8aa9ed'
cursor = 'c2b9a1'
cyan = '00617d'
cyan-hg = '43bfe0'
foreground = 'c2b9a1'
green = '787200'
green-hg = 'd9d138'
magenta = '5c2e40'
magenta-hg = 'ff8cb8'
red = '8e4317'
red-hg = 'f07935'
selection-background = 'c2b9a1'
selection-foreground = '1c1709'
white = 'c2b9a1'
white-hg = 'f2e8c9'
yellow = '945c00'
yellow-hg = 'ffab26'
