name = 'Taerminal'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '26282a'
black = '26282a'
black-hg = '6f6f6f'
blue = '8bbce5'
blue-hg = 'c2e3ff'
cursor = 'f0f0f0'
cyan = 'a2e1f8'
cyan-hg = 'c0e9f8'
foreground = 'f0f0f0'
green = 'b4fb73'
green-hg = 'd6fcba'
magenta = 'ffb2fe'
magenta-hg = 'ffc6ff'
red = 'ff8878'
red-hg = 'fe978b'
selection-background = 'f0f0f0'
selection-foreground = '26282a'
white = 'f1f1f1'
white-hg = 'ffffff'
yellow = 'fffcb7'
yellow-hg = 'fffed5'
