name = 'Tango-Dark'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '000000'
black = '000000'
black-hg = '545753'
blue = '3464a4'
blue-hg = '719ecf'
cursor = 'ffffff'
cyan = '05989a'
cyan-hg = '34e2e2'
foreground = 'ffffff'
green = '4e9a05'
green-hg = '8ae234'
magenta = '74507a'
magenta-hg = 'ad7ea7'
red = 'cc0000'
red-hg = 'ef2828'
selection-background = 'b4d5ff'
selection-foreground = '000000'
white = 'd3d7cf'
white-hg = 'ededec'
yellow = 'c4a000'
yellow-hg = 'fce94e'
