name = 'Tangoish'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '2e3436'
black = '2e3436'
black-hg = '2e3436'
blue = '3465a4'
blue-hg = '729fcf'
cursor = 'eeeeec'
cyan = 'f57900'
cyan-hg = 'fcaf3e'
foreground = 'eeeeec'
green = '73d216'
green-hg = '8ae234'
magenta = '75507b'
magenta-hg = 'ad7fa8'
red = 'cc0000'
red-hg = 'ef2929'
selection-background = 'eeeeec'
selection-foreground = '2e3436'
white = 'd3d7cf'
white-hg = 'eeeeec'
yellow = 'edd400'
yellow-hg = 'fce94f'
