name = 'Thwump'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '000000'
black = '202020'
black-hg = '505050'
blue = '7070a0'
blue-hg = '7070d0'
cursor = 'ffffff'
cyan = '70a0a0'
cyan-hg = '70d0d0'
foreground = 'ffffff'
green = '70a070'
green-hg = '70d070'
magenta = 'a070a0'
magenta-hg = 'd070d0'
red = 'a07070'
red-hg = 'd07070'
selection-background = 'ffffff'
selection-foreground = '000000'
white = 'a0a0a0'
white-hg = 'f0f0f0'
yellow = 'a0a070'
yellow-hg = 'd0d070'
