name = 'Tlh'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '101010'
black = '1c1c1c'
black-hg = '4d4d4d'
blue = '4695c8'
blue-hg = '5a9dc8'
cursor = '66ff66'
cyan = '43afce'
cyan-hg = '69b8ce'
foreground = '66ff66'
green = '60ff60'
green-hg = '70ff70'
magenta = 'a78edb'
magenta-hg = 'b29fdb'
red = 'd81860'
red-hg = 'f00060'
selection-background = '66ff66'
selection-foreground = '101010'
white = 'f3ebe2'
white-hg = 'eeeeee'
yellow = 'f9fd75'
yellow-hg = 'f9fd80'
