name = 'Tomorrow-Night-Bright'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '000000'
black = '000000'
black-hg = '000000'
blue = '79a6da'
blue-hg = '79a6da'
cursor = 'e9e9e9'
cyan = '70c0b1'
cyan-hg = '70c0b1'
foreground = 'e9e9e9'
green = 'b9c949'
green-hg = 'b9c949'
magenta = 'c396d7'
magenta-hg = 'c396d7'
red = 'd44d53'
red-hg = 'd44d53'
selection-background = '424242'
selection-foreground = '000000'
white = 'fffefe'
white-hg = 'fffefe'
yellow = 'e6c446'
yellow-hg = 'e6c446'
