name = 'ToyChest'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '23364a'
black = '2c3f57'
black-hg = '326889'
blue = '325d96'
blue-hg = '33a5d9'
cursor = 'd4d4d4'
cyan = '35a08f'
cyan-hg = '41c3ad'
foreground = '30cf7b'
green = '199171'
green-hg = '30cf7b'
magenta = '8a5ddb'
magenta-hg = 'ad6bdc'
red = 'be2d26'
red-hg = 'dd5943'
selection-background = '5f207a'
selection-foreground = '23364a'
white = '23d082'
white-hg = 'd4d4d4'
yellow = 'da8e26'
yellow-hg = 'e7d74b'
