name = 'Twilight-light'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = 'ffffff'
black = '1e1e1e'
black-hg = '5f5a60'
blue = '7587a6'
blue-hg = '7587a6'
cursor = '464b50'
cyan = 'afc4db'
cyan-hg = 'afc4db'
foreground = '464b50'
green = '8f9d6a'
green-hg = '8f9d6a'
magenta = '9b859d'
magenta-hg = '9b859d'
red = 'cf6a4c'
red-hg = 'cf6a4c'
selection-background = '464b50'
selection-foreground = 'ffffff'
white = 'a7a7a7'
white-hg = 'ffffff'
yellow = 'f9ee98'
yellow-hg = 'f9ee98'
