name = 'Vacuous2'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '101010'
black = '202020'
black-hg = '606060'
blue = '356579'
blue-hg = '7491a1'
cursor = 'd2c5bc'
cyan = '0b3452'
cyan-hg = '0f829d'
foreground = 'd2c5bc'
green = '81957c'
green-hg = 'a7b79a'
magenta = '2d2031'
magenta-hg = '87314e'
red = 'b91e2e'
red-hg = 'd14548'
selection-background = 'd2c5bc'
selection-foreground = '101010'
white = '909090'
white-hg = 'fff0f0'
yellow = 'f9bb80'
yellow-hg = 'fae3a0'
