name = 'Vue'

[extras]
vscode = ['Vue Theme']
wallpaper = ['~/.config/gtheme/wallpapers/Vue/odin-dark.jpg']

[colors]
background = '002b36'
black = '000000'
black-hg = '808080'
blue = '19f9d8'
blue-hg = '19f9d8'
cursor = 'e6e6e6'
cyan = '09cbdd'
cyan-hg = '09cbdd'
foreground = 'e6e6e6'
green = '19f9d8'
green-hg = '19f9d8'
magenta = 'f48fb1'
magenta-hg = 'f48fb1'
red = 'ee475e'
red-hg = 'ee475e'
selection-background = '46494d'
selection-foreground = 'e6e6e6'
white = 'e6e6e6'
white-hg = 'e6e6e6'
yellow = 'ffcc95'
yellow-hg = 'ffcc95'
