name = 'Wryan'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '101010'
black = '333333'
black-hg = '3d3d3d'
blue = '395573'
blue-hg = '477ab3'
cursor = '9d9eca'
cyan = '31658c'
cyan-hg = '6096bf'
foreground = '999993'
green = '287373'
green-hg = '53a6a6'
magenta = '5e468c'
magenta-hg = '7e62b3'
red = '8c4665'
red-hg = 'bf4d80'
selection-background = '4d4d4d'
selection-foreground = '101010'
white = '899ca1'
white-hg = 'c0c0c0'
yellow = '7c7c99'
yellow-hg = '9e9ecb'
