name = 'XTerm'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '000000'
black = '000000'
black-hg = '7f7f7f'
blue = '0000ee'
blue-hg = '5c5cff'
cursor = 'ffffff'
cyan = '00cdcd'
cyan-hg = '00ffff'
foreground = 'ffffff'
green = '00cd00'
green-hg = '00ff00'
magenta = 'cd00cd'
magenta-hg = 'ff00ff'
red = 'cd0000'
red-hg = 'ff0000'
selection-background = 'ffffff'
selection-foreground = '000000'
white = 'e5e5e5'
white-hg = 'ffffff'
yellow = 'cdcd00'
yellow-hg = 'ffff00'
