name = 'Zenburn'

[extras]
vscode = ['']
wallpaper = ['']

[colors]
background = '3f3f3f'
black = '4d4d4d'
black-hg = '709080'
blue = '506070'
blue-hg = '94bff3'
cursor = '73635a'
cyan = '8cd0d3'
cyan-hg = '93e0e3'
foreground = 'dcdccc'
green = '60b48a'
green-hg = 'c3bf9f'
magenta = 'dc8cc3'
magenta-hg = 'ec93d3'
red = '705050'
red-hg = 'dca3a3'
selection-background = '21322f'
selection-foreground = '3f3f3f'
white = 'dcdccc'
white-hg = 'ffffff'
yellow = 'f0deae'
yellow-hg = 'dfcf9f'
